wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    session_history: code/_session_history.ipynb
    start_time: 1686561271.282255
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      4: 3.9.6
      5: 0.13.10
      6: 4.29.2
      8:
      - 1
      - 5
